### ISSUE TITLE
rosdep error after CATKIN_IGNORE-ing o3d3xx

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial-consortium/A5#5]
After placing a `CATKIN_IGNORE` marker in the `o3d3xx` package dir as instructed in the readme ([here](https://github.com/ros-industrial-consortium/A5/blame/045d9ceba969f5040d84dd8d3008fbe06d6ebfd6/README.md#L37-L38)), running `rosdep check --from-paths src -i` results in the following error:

```
ERROR[a5_calibration]: Cannot locate rosdep definition for [o3d3xx]
        rosdep key : o3d3xx
        OS name    : ubuntu
        OS version : xenial
        Data: <no data>
```

**Comment by gavanderhoorn** [comment]
This is of course expected as `o3d3xx` can then no longer be found in the workspace and has no binary installation candidates.

**Comment by Jmeyer1292** [comment]
I suppose you could ignore calibration too. When building we could blacklist these packages if you're running in simulation only. For all the rosdep stuff, im not sure what the best answer is. I could put all hardware specific stuff under a folder and ignore that.

Suggestions @gavanderhoorn ?

**Comment by gavanderhoorn** [comment]
@Jmeyer1292: an alternative to `CATKIN_IGNORE`ing the pkg would be to make `catkin` put it on its blacklist. I've done that in #7.

**Comment by gavanderhoorn** [comment]
Work-around in #7 was merged.
